# Generated by Django 5.1.5 on 2025-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_deposit_deposit_for_deposit_deposit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposit_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
