# Generated by Django 5.1.5 on 2025-01-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deposit_deposit_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_for',
        ),
    ]
