# Generated by Django 5.1.5 on 2025-01-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_deposit_deposit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_type',
            field=models.CharField(choices=[('tithe', 'Tithe'), ('thanksgiving', 'Thanksgiving'), ('wedding', 'Wedding'), ('offertory', 'Offertory'), ('first_fruits', 'First Fruit'), ('department_registration', 'Department Registration'), ('church_projects', 'Church Project'), ('others', 'Others')], default='offertory', max_length=100),
        ),
    ]
